### ISSUE TITLE
Upgrade to graphql 0.7.2

### ISSUE THREAD

**Issue by julian-rare** [apollographql/optics-agent-js#75]
Currently fails trying to run optics with graphql 0.7.2

**Comment by pcarrier** [comment]
Hi @julian-rare, Optics should work fine with graphql 0.7.2.

Could you please tell us more about the issues you are facing?

**Comment by cmmcleod** [comment]
Maybe this should be [0.9.1](https://github.com/graphql/graphql-js/releases). Would be nice since 0.9.0 has some flow fixes.

**Comment by pcarrier** [comment]
We are already compatible, as far as we can tell and claim in npm, with:

```
    "graphql": "^0.6.2 || ^0.7.0 || ^0.8.0 || ^0.9.0",
```

**Comment by cmmcleod** [comment]
Peer dependencies aren't updated though

https://github.com/apollographql/optics-agent-js/blob/master/package.json#L39

**Comment by pcarrier** [comment]
@cmmcleod oops sorry about that, thanks for the report. Published 1.1.1 with a fix.
