### ISSUE TITLE
How to use with Meteor

### ISSUE THREAD

**Issue by clayne11** [apollographql/optics-agent-js#84]
I tried adding the middleware by doing:

```javascript
WebApp.connectHandlers.use(Meteor.bindEnvironment(OpticsAgent.middleware()))
```

but I'm getting the error `Optics context not found. Make sure Optics middleware is installed.`

**Comment by clayne11** [comment]
I had to put the middleware before the GraphQL server. Seems to be working now.

**Comment by pcarrier** [comment]
Hi @clayne11, please note that we offer official support to our customers:
![support in the UI](https://cloud.githubusercontent.com/assets/8641/22934581/4aac3ab0-f284-11e6-82c3-4c847679d4d3.png)
