### ISSUE TITLE
does it work with relay server?

### ISSUE THREAD

**Issue by sibelius** [apollographql/optics-agent-js#88]

**Comment by rohit2b** [comment]
Hi @sibelius - Optics works with apps that use Relay on the client. Can you point me towards what kind of server you are using?

**Comment by sibelius** [comment]
I've tried to add it here: https://github.com/entria/graphql-dataloader-boilerplate

it sad the optics context was missing

**Comment by sibelius** [comment]
it does not work well with koa-graphql https://github.com/chentsulin/koa-graphql/blob/master/src/index.js#L100

I'll send a PR to fix this

**Comment by rohit2b** [comment]
Thanks, will take a look at this
