### ISSUE TITLE
Optics agent seems to prevent Node to shutdown

### ISSUE THREAD

**Issue by vanwalj** [apollographql/optics-agent-js#94]
Hello,

Since the latest version it seems that you intercept SIGINT without properly exiting 

https://github.com/apollographql/optics-agent-js/commit/864134711e3ebfeb816091e187c46e5517e2df9f#diff-224869730a5b5fad7d7aa8feb091db60R92

Not a big deal, but it prevent my server from exiting when I CTRL+C for example ;)

**Comment by rohit2b** [comment]
Thanks! We'll take a look at this.

**Comment by gajus** [comment]
This one is ridiculously annoying, esp. in development environment.

For other stumbling across this, simply configure `shutdownGracefully: false` in development environment.
