### ISSUE TITLE
Usage with React Native

### ISSUE THREAD

**Issue by sonaye** [apollographql/optics-agent-js#96]
Can Optics be integrated with React Native? I can see [here](https://github.com/apollographql/optics-agent-js#add-the-middleware) that a middleware is needed.

**Comment by rohit2b** [comment]
Optics works with client apps written in React Native.

[This](https://github.com/apollographql/optics-agent-js#add-the-middleware) refers to GraphQL server middleware - for example Express and HAPI. There is no different server middleware needed for React Native.
